DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT
(
	 ID 		INT 			AUTO_INCREMENT PRIMARY KEY
	,NAME		VARCHAR(20)		NOT NULL
	,MARK1		INT
	,MARK2		INT
	,MARK3		INT
	,TOTAL		INT
	,GRADE		CHAR(4)
);